name: geowq
channels:
- conda-forge
dependencies:
        - python<3.10
        - pandas        
        - pytest
        - yapf
        - matplotlib
        - geopandas
        - cartopy
        - h3pandas
        - xarray
        - rioxarray
        - earthengine-api
        - seaborn
        - geocube
        #
        # - scikit-learn
        # - tabulate
        # - geojson        
        # - utm
        # - dataretrieval
        # - scikit-image
        # rivgraph deps
        # - loguru
        # - fastdtw
