name: geowq
channels:
- conda-forge
dependencies:
        - python<3.10
        - pandas        
        - pytest
        - yapf
        - matplotlib
        - scikit-learn
        - seaborn
        - geopandas
        - tabulate
        - geojson
        - earthengine-api
        - cartopy
