name: geowq
channels:
- conda-forge
dependencies:
        - python>3
        - pandas        
        - pytest
        - yapf
        - matplotlib
        - scikit-learn
        - seaborn
        - geopandas
        - tabulate
